### ISSUE TITLE
Add Github Workflow

### ISSUE THREAD

**Issue by rrpadilla** [Dewbud/CardConnect#9]
Hi,
are you ok adding the following github workflow to run the tests every time a PR is created?

See: https://github.com/rrpadilla/CardConnect/blob/master/.github/workflows/ci.yml

You can see it working [here](https://github.com/rrpadilla/CardConnect/runs/790029876?check_suite_focus=true).

```yml
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }}
    env:
      extensions: php-json, curl, mbstring
      key: cache-v1 # can be any string, change to clear the extension cache.

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}

      # Composer Cache
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
          
      # Cache PHP dependencies
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
    
      # Composer install dependencies
      - name: Install dependencies
        uses: php-actions/composer@v1

      # Runs tests
      - name: Execute tests
        run: vendor/bin/phpunit --verbose
```

Thanks
